### ISSUE TITLE
[QUESTION] Should we redesign BotANF in another language?

### ISSUE THREAD

**Issue by anf** [anf/BotANF#15]
**What's the question?**
I just had this crazy idea to redesign BotANF, in another language. v1 is based on C#, redoing it again just gets boring. Why not try it in some other language that I know, that would also be fun and a new learning experience. Some of my known languages that also have a library are:
- JavaScript/TypeScript
- Rust
- Python
- ~~C++~~ // It's kind of a pain to import a lib with C++.

Keeping in mind that we also have MongoDB support, these languages would be awesome.

#### I think we should go for TypeScript because:
1. TypeScript is a really fun and cool semi-OOP language
2. I haven't used it very much, it would be nice to explore more of it
3. It's well documented
4. Being able to be converted into JavaScript, it would be wayyy more easier for me to host on heroku and not host it locally, which would be a life saver
5. The chat-bot module of BotANF is written in JavaScript, so that would be cool to use it there and host the rest of it
6. Because TypeScript

#### I think we should go for Rust because:
1. It's a completely new language for me which I haven't learnt very much, it's a really interesting language and I'm impressed by how it works
2. I haven't used Rust in any project
3. I found a [repo](https://github.com/rust-lang/crates-io-ops-bot) that apparently shows that it's a discord bot and can be hosted on heroku.

#### I think we should go for Python because:
1. Heroku support
2. Python is an easy language, at least for me
3. Again, as Rust, I haven't really used it *that much*
4. Because of point 3, it would be a new learning experience

#### I think we should go for C++ because:
1. No
2. Just no
3. I want to remain sane, just don't talk about it

<h2 align="center">What are your thoughts on it?</h2>
<br/>
<br/>
<br/>

**Comment by rushilkoul** [comment]
interesting indeed. what I can suggest is choose typescript, cuz well being able to be converted into JavaScript, it would be easy to host on heroku. apparently there's a chat-bot module of BotANF that's also written in js, so it would all be hosted easily?

again, TS is very well documented, and since you haven't really gotten around to explore it yet, I really suggest you do. It'll be a fun experience for you too and at the end of the day you'll have learnt another language well and also not have to worry about hosting issues, hence being a lifesaver

again, do what you wanna do, but I suggest you **to use TypeScript.**

**Comment by Juptian** [comment]
DiscordJS, Discord doesn't have an official C++ lib, and its a pain in the ass. I would say use TS or JS

**Comment by rushilkoul** [comment]
TS all the way

**Comment by ghost** [comment]
C++ is going to be pain, Python is nice, I haven't used it much with Discord and stuff, I'm pretty sure you'll like it.

As for Rust, I _don't really_ think it will compare to TS and Python their advantages here (along with Python and TS being a bit more easy), so yeah, TS or Python, TS has more advantages,Python is a great languages with it's advantages ,but you might just like TS more because TypeScript

**Comment by tomlin7** [comment]
# Python
Python is a great choice, **Discord.py** is one of the most advanced discord API wrappers out there, also you will not have to over-confuse things when using discord.py, i'm not gonna suggest rust, because currently there is no well-known and advanced API(compared to discord.js, discord.py) wrapper for rust, and there is no such active community for discord rust api wrappers, rust is a growing language, so rust is a nono. My suggestion is **python** (*discord.py*).

**Comment by Yeffian** [comment]
**KOTLIN**
Ive seen some server's that use Kotlin for discord bots, might be a intresting experiment, but if you dont want to go down a path of confusion, I say Python

**Comment by mellobacon** [comment]
Hmm Python and TS both have great libraries. I say since it would be easier for you to integrate the chat bot and host on heroku, go with TS.

**Comment by TheXorbParadox** [comment]
c++ cus it's gonna ba a paaaain in your ass..jk

i'd not recommend python cus i've heard it's slow, and you don't want your bots to be slow
i don't know about typescript but you don't seem excited about it
you seem to be pretty excited about rust so i'd say go with it.

but if you want your bot to be really fast..(yeah read the first line)

**Comment by Pheubel** [comment]
Personally i would do it in C++ as it would teach me a lot about the language, and out of the languages displayed here it is the most likely one that i would be using in the next 10 years. Python and javascript are a hard no for me due to their dynamic nature. Typescript is ok in terms of writing but it is still javascript under the hood.

so that leaves either rust or C++ for me and because C++ is more used in my fields of interest that is where my preference lies.
</opinion>

**Comment by mickelelkhoury** [comment]
IMO using JS/TS or Python are two great choices, saying you have knowledge in both of them this might be the obvious answer for you question. I have no knowledge is rust nor think this might be as good as the others, also Python might be the one to go.

**Comment by anf** [comment]
Hey everyone, thank you for your cooperation and suggestions on this issue. From your feedback and discussions with the team, we've considered to use TypeScript for the development process. Thank you for your time.
